language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp
script: gulp travis
branches:
  except:
    - gh-pages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
      - calibre
env:
  - CXX=g++-4.9
before_install:
  - npm explore npm -g -- npm install node-gyp@latest